const Flor = require("../models/Flor");

/* --------------------------------------------------------------------------
   Catálogo COMPLETO — 70 flores do Floriografia
   -------------------------------------------------------------------------- */
const FLORES_SEED = [
  { nome:"Rosa Vermelha", especie:"Rosa spp.", cor:"Vermelho", emoji:"🌹", file:"rosa_vermelha.png",
    feelings:["Amor"], meanings:["Amor profundo","Paixão","Desejo","Romance"],
    colors:["Vermelho"], category:"Amor", origin:"Ásia", season:"Primavera / Verão",
    occasions:["Dia dos Namorados","Casamento","Aniversário","Pedido de Desculpas"],
    descricao:"A rosa vermelha é o símbolo máximo do amor e da paixão. É a flor mais associada a pedidos e declarações sinceras.",
    preco:15.90, estoque:100 },

  { nome:"Girassol", especie:"Helianthus annuus", cor:"Amarelo", emoji:"🌻", file:"girassol.png",
    feelings:["Alegria","Esperança"], meanings:["Alegria","Positividade","Vitalidade"],
    colors:["Amarelo"], category:"Alegria", origin:"América do Norte", season:"Verão",
    occasions:["Aniversário","Amizade","Parabéns","Gratidão"],
    descricao:"O girassol gira em direção ao sol. É a flor da energia, do otimismo e da lealdade.",
    preco:12.50, estoque:80 },

  { nome:"Tulipa Rosa", especie:"Tulipa gesneriana", cor:"Rosa", emoji:"🌷", file:"tulipa_rosa.png",
    feelings:["Amor","Amizade"], meanings:["Carinho","Cuidado","Afeto"],
    colors:["Rosa"], category:"Afeto", origin:"Ásia Central", season:"Primavera",
    occasions:["Amizade","Aniversário","Gratidão","Parabéns"],
    descricao:"A tulipa rosa fala de afeto gentil e cuidado cotidiano.",
    preco:18.00, estoque:60 },

  { nome:"Lavanda", especie:"Lavandula angustifolia", cor:"Roxo", emoji:"🪻", file:"lavanda.png",
    feelings:["Tranquilidade","Esperança"], meanings:["Tranquilidade","Equilíbrio","Paz"],
    colors:["Roxo","Lilás"], category:"Tranquilidade", origin:"Mediterrâneo", season:"Verão",
    occasions:["Condolências","Gratidão","Amizade","Dia dos Namorados"],
    descricao:"A lavanda acalma os sentidos. Seu perfume traz serenidade e sensação de lar.",
    preco:22.00, estoque:50 },

  { nome:"Lírio Branco", especie:"Lilium candidum", cor:"Branco", emoji:"🌸", file:"lirio_branco.png",
    feelings:["Esperança","Tranquilidade"], meanings:["Pureza","Inocência","Renovação"],
    colors:["Branco"], category:"Pureza", origin:"Europa / Ásia", season:"Primavera / Verão",
    occasions:["Casamento","Condolências","Gratidão","Aniversário"],
    descricao:"O lírio branco simboliza pureza e recomeços.",
    preco:20.00, estoque:40 },

  { nome:"Peônia", especie:"Paeonia lactiflora", cor:"Rosa", emoji:"🌺", file:"peonia.png",
    feelings:["Amor","Alegria"], meanings:["Prosperidade","Honra","Romance feliz"],
    colors:["Rosa","Branco"], category:"Prosperidade", origin:"Ásia", season:"Primavera",
    occasions:["Casamento","Parabéns","Aniversário","Dia dos Namorados"],
    descricao:"A peônia é a rainha das flores. Representa abundância e bons presságios.",
    preco:25.00, estoque:45 },

  { nome:"Orquídea Roxa", especie:"Phalaenopsis spp.", cor:"Roxo", emoji:"💮", file:"orquidea_roxa.png",
    feelings:["Amor","Gratidão"], meanings:["Beleza","Amor","Refinamento"],
    colors:["Roxo"], category:"Admiração", origin:"Ásia / Oceania", season:"Ano inteiro",
    occasions:["Gratidão","Aniversário","Parabéns","Dia dos Namorados"],
    descricao:"A orquídea roxa é sofisticada e resistente — admiração profunda e amor paciente.",
    preco:35.00, estoque:30 },

  { nome:"Margarida", especie:"Leucanthemum vulgare", cor:"Branco", emoji:"🌼", file:"margarida.png",
    feelings:["Amizade","Alegria"], meanings:["Inocência","Lealdade","Amizade"],
    colors:["Branco","Amarelo"], category:"Amizade", origin:"Europa", season:"Primavera / Verão",
    occasions:["Amizade","Aniversário","Gratidão","Pedido de Desculpas"],
    descricao:"Simples e sincera, a margarida é a flor das amizades verdadeiras.",
    preco:8.00, estoque:120 },

  { nome:"Jasmim", especie:"Jasminum officinale", cor:"Branco", emoji:"🤍", file:"jasmim.png",
    feelings:["Amor","Tranquilidade"], meanings:["Amor eterno","Espiritualidade","Doçura"],
    colors:["Branco"], category:"Amor", origin:"Ásia", season:"Primavera / Verão",
    occasions:["Casamento","Dia dos Namorados","Condolências","Gratidão"],
    descricao:"O jasmim exala um perfume doce que só se revela à noite.",
    preco:24.00, estoque:40 },

  { nome:"Cravo Vermelho", especie:"Dianthus caryophyllus", cor:"Vermelho", emoji:"🌺", file:"cravo_vermelho.png",
    feelings:["Coragem","Amor"], meanings:["Admiração","Coragem","Paixão"],
    colors:["Vermelho"], category:"Admiração", origin:"Mediterrâneo", season:"Ano inteiro",
    occasions:["Parabéns","Aniversário","Dia dos Namorados","Gratidão"],
    descricao:"O cravo vermelho é a flor da coragem e da admiração.",
    preco:10.00, estoque:80 },

  { nome:"Hortênsia Azul", especie:"Hydrangea macrophylla", cor:"Azul", emoji:"💙", file:"hortensia_azul.png",
    feelings:["Gratidão","Tranquilidade"], meanings:["Gratidão","Abundância","Sinceridade"],
    colors:["Azul"], category:"Gratidão", origin:"Ásia / América", season:"Verão",
    occasions:["Gratidão","Casamento","Amizade","Condolências"],
    descricao:"A hortênsia floresce em cachos generosos, simbolizando gratidão e abundância.",
    preco:28.00, estoque:35 },

  { nome:"Íris Roxa", especie:"Iris germanica", cor:"Roxo", emoji:"🪻", file:"iris_roxa.png",
    feelings:["Esperança","Coragem"], meanings:["Esperança","Sabedoria","Coragem"],
    colors:["Roxo"], category:"Esperança", origin:"Europa", season:"Primavera",
    occasions:["Pedido de Desculpas","Condolências","Parabéns","Gratidão"],
    descricao:"Na mitologia, a íris era a mensageira dos deuses.",
    preco:19.00, estoque:45 },

  { nome:"Campânula", especie:"Campanula medium", cor:"Azul", emoji:"🔔", file:"campanula.png",
    feelings:["Tranquilidade","Esperança"], meanings:["Gratidão","Humildade","Constância"],
    colors:["Azul","Roxo"], category:"Gratidão", origin:"Europa", season:"Primavera / Verão",
    occasions:["Gratidão","Amizade","Condolências","Aniversário"],
    descricao:"A campânula balança suavemente ao vento, como sinos silenciosos.",
    preco:14.00, estoque:55 },

  { nome:"Tulipa Roxa", especie:"Tulipa gesneriana", cor:"Roxo", emoji:"🪻", file:"tulipa_roxa.png",
    feelings:["Amor","Tranquilidade"], meanings:["Realeza","Admiração","Espiritualidade"],
    colors:["Roxo"], category:"Admiração", origin:"Ásia Central", season:"Primavera",
    occasions:["Casamento","Aniversário","Dia dos Namorados","Gratidão"],
    descricao:"A tulipa roxa é a tulipa da realeza.",
    preco:19.00, estoque:40 },

  { nome:"Lótus Roxo", especie:"Nelumbo nucifera", cor:"Roxo", emoji:"🪷", file:"lotus_roxo.png",
    feelings:["Esperança","Tranquilidade"], meanings:["Iluminação","Renascimento","Pureza espiritual"],
    colors:["Roxo","Rosa"], category:"Espiritualidade", origin:"Ásia", season:"Verão",
    occasions:["Casamento","Condolências","Aniversário","Gratidão"],
    descricao:"O lótus nasce do lodo e floresce limpo — símbolo de renascimento.",
    preco:32.00, estoque:25 },

  { nome:"Narciso", especie:"Narcissus poeticus", cor:"Amarelo", emoji:"🌼", file:"narciso.png",
    feelings:["Alegria","Esperança"], meanings:["Renovação","Autoestima","Primavera"],
    colors:["Amarelo","Branco"], category:"Alegria", origin:"Europa", season:"Primavera",
    occasions:["Aniversário","Parabéns","Amizade","Pedido de Desculpas"],
    descricao:"O narciso anuncia a primavera. É a flor do recomeço e da autoestima.",
    preco:13.00, estoque:70 },

  { nome:"Crocus", especie:"Crocus sativus", cor:"Roxo", emoji:"🟣", file:"crocus.png",
    feelings:["Esperança","Alegria"], meanings:["Renascimento","Ousadia","Alegria"],
    colors:["Roxo","Lilás"], category:"Esperança", origin:"Mediterrâneo", season:"Primavera",
    occasions:["Aniversário","Parabéns","Gratidão","Recomeço"],
    descricao:"O crocus fura a neve para florescer — prova de que a beleza sempre volta.",
    preco:11.00, estoque:60 },

  { nome:"Camélia Rosa", especie:"Camellia japonica", cor:"Rosa", emoji:"🌺", file:"camelia_rosa.png",
    feelings:["Amor","Gratidão"], meanings:["Admiração","Perfeição","Devotamento"],
    colors:["Rosa"], category:"Amor", origin:"Ásia", season:"Inverno / Primavera",
    occasions:["Dia dos Namorados","Casamento","Gratidão","Aniversário"],
    descricao:"A camélia floresce quando quase nada floresce.",
    preco:26.00, estoque:30 },

  { nome:"Camélia Vermelha", especie:"Camellia japonica", cor:"Vermelho", emoji:"🌹", file:"camelia_vermelha.png",
    feelings:["Amor","Coragem"], meanings:["Amor ardente","Coragem","Reconhecimento"],
    colors:["Vermelho"], category:"Amor", origin:"Ásia", season:"Inverno / Primavera",
    occasions:["Dia dos Namorados","Parabéns","Casamento","Aniversário"],
    descricao:"A camélia vermelha é a flor do amor que não teme o inverno.",
    preco:27.00, estoque:28 },

  { nome:"Lótus Azul", especie:"Nymphaea caerulea", cor:"Azul", emoji:"🪷", file:"lotus_azul.png",
    feelings:["Tranquilidade","Esperança"], meanings:["Sabedoria","Renascimento","Paz interior"],
    colors:["Azul"], category:"Espiritualidade", origin:"África / Ásia", season:"Verão",
    occasions:["Condolências","Casamento","Aniversário","Gratidão"],
    descricao:"O lótus azul era sagrado no Egito antigo — símbolo de renascimento e sabedoria.",
    preco:33.00, estoque:22 },

  { nome:"Papoula", especie:"Papaver rhoeas", cor:"Vermelho", emoji:"🌺", file:"papoula.png",
    feelings:["Saudade","Amor"], meanings:["Memória","Consolo","Sono eterno"],
    colors:["Vermelho"], category:"Memória", origin:"Europa", season:"Primavera / Verão",
    occasions:["Condolências","Aniversário","Dia dos Namorados","Amizade"],
    descricao:"A papoula é a flor da lembrança.",
    preco:9.00, estoque:90 },

  { nome:"Miosótis", especie:"Myosotis", cor:"Azul", emoji:"💙", file:"miosotis.png",
    feelings:["Saudade","Amizade"], meanings:["Lembrança","Amor verdadeiro","Fidelidade"],
    colors:["Azul"], category:"Memória", origin:"Europa", season:"Primavera",
    occasions:["Amizade","Dia dos Namorados","Condolências","Gratidão"],
    descricao:'"Não me esqueças" — é o que o miosótis diz em silêncio.',
    preco:12.00, estoque:75 },

  { nome:"Lírio Estrela", especie:"Lilium orientalis", cor:"Rosa", emoji:"🌸", file:"lirio_estrela.png",
    feelings:["Amor","Alegria"], meanings:["Ambição","Prosperidade","Pureza"],
    colors:["Rosa","Branco"], category:"Prosperidade", origin:"Ásia", season:"Verão",
    occasions:["Casamento","Parabéns","Aniversário","Gratidão"],
    descricao:"O lírio-estrela abre suas pétalas como uma constelação.",
    preco:23.00, estoque:42 },

  { nome:"Centáurea", especie:"Centaurea cyanus", cor:"Azul", emoji:"💠", file:"centaurea.png",
    feelings:["Esperança","Amizade"], meanings:["Delicadeza","Lealdade","Sinceridade"],
    colors:["Azul"], category:"Amizade", origin:"Europa", season:"Verão",
    occasions:["Amizade","Gratidão","Aniversário","Pedido de Desculpas"],
    descricao:"A centáurea cresce em campos de trigo — símbolo de lealdade simples.",
    preco:10.50, estoque:65 },

  { nome:"Copo-de-leite", especie:"Zantedeschia aethiopica", cor:"Branco", emoji:"🤍", file:"copo_de_leite.png",
    feelings:["Esperança","Tranquilidade"], meanings:["Pureza","Inocência","Renascimento"],
    colors:["Branco"], category:"Pureza", origin:"África do Sul", season:"Primavera",
    occasions:["Casamento","Condolências","Gratidão","Aniversário"],
    descricao:"Flor elegante — símbolo de pureza e novos começos.",
    preco:21.00, estoque:50 },

  { nome:"Zínia", especie:"Zinnia elegans", cor:"Vermelho", emoji:"🌺", file:"zinia.png",
    feelings:["Alegria","Amizade"], meanings:["Amizade eterna","Lembrança","Resistência"],
    colors:["Vermelho","Rosa"], category:"Amizade", origin:"América Central", season:"Verão",
    occasions:["Amizade","Aniversário","Gratidão","Parabéns"],
    descricao:"A zínia dura semanas depois de cortada — flor da amizade que resiste ao tempo.",
    preco:14.00, estoque:60 },

  { nome:"Rosa Azul", especie:"Rosa × hybrida", cor:"Azul", emoji:"🔷", file:"rosa_azul.png",
    feelings:["Amor","Esperança"], meanings:["Mistério","Impossível","Milagre"],
    colors:["Azul"], category:"Amor", origin:"Cultivada", season:"Ano inteiro",
    occasions:["Dia dos Namorados","Aniversário","Parabéns","Pedido de Desculpas"],
    descricao:"A rosa azul não existe na natureza — representa o impossível que se torna real.",
    preco:45.00, estoque:15 },

  { nome:"Flor de Cerejeira", especie:"Prunus serrulata", cor:"Rosa", emoji:"🌸", file:"flor_de_cerejeira.png",
    feelings:["Amor","Saudade"], meanings:["Efêmero","Renovação","Beleza passageira"],
    colors:["Rosa"], category:"Memória", origin:"Japão", season:"Primavera",
    occasions:["Aniversário","Amizade","Condolências","Dia dos Namorados"],
    descricao:"O sakura floresce por poucos dias — celebra a beleza do que é breve.",
    preco:30.00, estoque:20 },

  { nome:"Lilás", especie:"Syringa vulgaris", cor:"Lilás", emoji:"💜", file:"lilas.png",
    feelings:["Amor","Alegria"], meanings:["Primeiro amor","Juventude","Confiança"],
    colors:["Lilás","Roxo"], category:"Amor", origin:"Europa / Ásia", season:"Primavera",
    occasions:["Dia dos Namorados","Gratidão","Aniversário","Amizade"],
    descricao:"O lilás floresce em cachos que lembram a juventude.",
    preco:17.00, estoque:55 },

  { nome:"Hibisco", especie:"Hibiscus rosa-sinensis", cor:"Vermelho", emoji:"🌺", file:"hibisco.png",
    feelings:["Amor","Alegria"], meanings:["Paixão","Beleza delicada","Glória"],
    colors:["Vermelho"], category:"Admiração", origin:"Ásia", season:"Verão",
    occasions:["Dia dos Namorados","Parabéns","Aniversário","Amizade"],
    descricao:"O hibisco é tropical e intenso. Suas pétalas abertas representam glória.",
    preco:16.00, estoque:70 },

  { nome:"Violeta", especie:"Viola odorata", cor:"Roxo", emoji:"💜", file:"violeta.png",
    feelings:["Amor","Tranquilidade"], meanings:["Modéstia","Fidelidade","Amor oculto"],
    colors:["Roxo","Lilás"], category:"Amor", origin:"Europa", season:"Primavera",
    occasions:["Dia dos Namorados","Amizade","Gratidão","Aniversário"],
    descricao:"A violeta floresce baixinho, quase escondida.",
    preco:11.50, estoque:80 },

  { nome:"Lírio Laranja", especie:"Lilium bulbiferum", cor:"Laranja", emoji:"🧡", file:"lirio_laranja.png",
    feelings:["Alegria","Coragem"], meanings:["Paixão","Energia","Confiança"],
    colors:["Laranja"], category:"Alegria", origin:"Europa", season:"Verão",
    occasions:["Parabéns","Aniversário","Amizade","Gratidão"],
    descricao:"O lírio laranja é a chama do jardim.",
    preco:21.00, estoque:45 },

  { nome:"Prímula", especie:"Primula", cor:"Rosa", emoji:"🌺", file:"primula.png",
    feelings:["Amor","Alegria"], meanings:["Primeiro amor","Juventude","Esperança"],
    colors:["Rosa","Vermelho"], category:"Amor", origin:"Europa", season:"Primavera",
    occasions:["Aniversário","Dia dos Namorados","Gratidão","Amizade"],
    descricao:"A prímula é a primeira flor da primavera.",
    preco:10.00, estoque:75 },

  { nome:"Cravo-amarelo", especie:"Tagetes", cor:"Amarelo", emoji:"🌻", file:"cravo_amarelo.png",
    feelings:["Alegria","Saudade"], meanings:["Criatividade","Proteção","Lembrança"],
    colors:["Amarelo","Laranja"], category:"Alegria", origin:"México", season:"Verão / Outono",
    occasions:["Condolências","Aniversário","Gratidão","Parabéns"],
    descricao:"Também chamado de marigold, é a flor das festas e das memórias.",
    preco:9.50, estoque:85 },

  { nome:"Lírio Negro", especie:'Lilium "Black Beauty"', cor:"Preto", emoji:"🖤", file:"lirio_negro.png",
    feelings:["Amor","Saudade"], meanings:["Amor proibido","Mistério","Elegância"],
    colors:["Preto","Roxo"], category:"Memória", origin:"Cultivada", season:"Verão",
    occasions:["Dia dos Namorados","Condolências","Aniversário","Pedido de Desculpas"],
    descricao:"O lírio negro é um vinho profundo — amor que não se explica.",
    preco:40.00, estoque:18 },

  { nome:"Cravo Rosa", especie:"Dianthus caryophyllus", cor:"Rosa", emoji:"🌸", file:"cravo_rosa.png",
    feelings:["Gratidão","Amor"], meanings:["Gratidão materna","Memória","Carinho"],
    colors:["Rosa"], category:"Gratidão", origin:"Mediterrâneo", season:"Ano inteiro",
    occasions:["Gratidão","Condolências","Aniversário","Amizade"],
    descricao:"O cravo rosa é a flor do Dia das Mães.",
    preco:11.00, estoque:90 },

  { nome:"Cosmos", especie:"Cosmos bipinnatus", cor:"Rosa", emoji:"🌼", file:"cosmos.png",
    feelings:["Alegria","Tranquilidade"], meanings:["Ordem","Harmonia","Beleza simples"],
    colors:["Rosa","Branco"], category:"Tranquilidade", origin:"México", season:"Verão / Outono",
    occasions:["Amizade","Aniversário","Gratidão","Parabéns"],
    descricao:"O cosmos cresce em campo aberto, balançando com o vento.",
    preco:13.00, estoque:60 },

  { nome:"Magnólia", especie:"Magnolia", cor:"Branco", emoji:"🤍", file:"magnolia.png",
    feelings:["Amor","Esperança"], meanings:["Dignidade","Pureza","Nobreza"],
    colors:["Branco","Rosa"], category:"Pureza", origin:"Ásia / América", season:"Primavera",
    occasions:["Casamento","Aniversário","Condolências","Gratidão"],
    descricao:"A magnólia é uma das flores mais antigas do mundo.",
    preco:29.00, estoque:25 },

  { nome:"Anêmona", especie:"Anemone coronaria", cor:"Roxo", emoji:"💜", file:"anemona.png",
    feelings:["Amor","Tranquilidade"], meanings:["Proteção","Antecipação","Sinceridade"],
    colors:["Roxo","Lilás"], category:"Admiração", origin:"Mediterrâneo", season:"Primavera",
    occasions:["Amizade","Casamento","Gratidão","Aniversário"],
    descricao:"Segundo a lenda, a anêmona nasceu das lágrimas de Afrodite.",
    preco:15.00, estoque:50 },

  { nome:"Anêmona Branca", especie:"Anemone coronaria", cor:"Branco", emoji:"🌸", file:"anemona_branca.png",
    feelings:["Esperança","Saudade"], meanings:["Sinceridade","Fragilidade","Antecipação"],
    colors:["Branco"], category:"Pureza", origin:"Mediterrâneo", season:"Primavera",
    occasions:["Condolências","Aniversário","Amizade","Casamento"],
    descricao:"A anêmona branca é pura e sincera.",
    preco:15.00, estoque:48 },

  { nome:"Crisântemo", especie:"Chrysanthemum morifolium", cor:"Amarelo", emoji:"🏵️", file:"crisantemo.png",
    feelings:["Alegria","Esperança"], meanings:["Longevidade","Nobreza","Alegria"],
    colors:["Amarelo","Branco","Roxo"], category:"Prosperidade", origin:"Ásia", season:"Outono",
    occasions:["Aniversário","Parabéns","Gratidão","Condolências"],
    descricao:"O crisântemo é a flor imperial do Japão.",
    preco:17.00, estoque:65 },

  { nome:"Dália", especie:"Dahlia pinnata", cor:"Vermelho", emoji:"💐", file:"dalia.png",
    feelings:["Alegria","Amor"], meanings:["Elegância","Criatividade","Dignidade"],
    colors:["Vermelho","Rosa","Roxo","Amarelo"], category:"Admiração", origin:"México", season:"Verão / Outono",
    occasions:["Parabéns","Aniversário","Casamento","Gratidão"],
    descricao:"A dália é a flor nacional do México.",
    preco:20.00, estoque:45 },

  { nome:"Frésia", especie:"Freesia refracta", cor:"Branco", emoji:"🌿", file:"fresia.png",
    feelings:["Amizade","Alegria"], meanings:["Inocência","Amizade","Confiança"],
    colors:["Branco","Amarelo"], category:"Amizade", origin:"África do Sul", season:"Primavera",
    occasions:["Amizade","Aniversário","Gratidão","Pedido de Desculpas"],
    descricao:"A frésia tem um perfume doce e inconfundível.",
    preco:18.00, estoque:55 },

  { nome:"Jacinto", especie:"Hyacinthus orientalis", cor:"Roxo", emoji:"🪴", file:"jacinto.png",
    feelings:["Amor","Tranquilidade"], meanings:["Constância","Devoção","Renovação"],
    colors:["Roxo","Rosa","Branco","Azul"], category:"Amor", origin:"Mediterrâneo", season:"Primavera",
    occasions:["Dia dos Namorados","Aniversário","Gratidão","Casamento"],
    descricao:"Na mitologia grega, o jacinto nasceu do sangue de um jovem amado por Apolo.",
    preco:16.00, estoque:60 },

  { nome:"Boca-de-leão", especie:"Antirrhinum majus", cor:"Vermelho", emoji:"🌾", file:"boca_de_leao.png",
    feelings:["Coragem","Alegria"], meanings:["Força","Graça","Proteção"],
    colors:["Vermelho","Rosa","Amarelo","Laranja"], category:"Coragem", origin:"Mediterrâneo", season:"Verão",
    occasions:["Parabéns","Aniversário","Amizade","Gratidão"],
    descricao:"A boca-de-leão abre suas pétalas como uma boca quando pressionada.",
    preco:13.50, estoque:70 },

  { nome:"Dente-de-leão", especie:"Taraxacum officinale", cor:"Amarelo", emoji:"🍀", file:"dente_de_leao.png",
    feelings:["Esperança","Alegria"], meanings:["Resiliência","Desejos","Liberdade"],
    colors:["Amarelo"], category:"Esperança", origin:"Europa", season:"Primavera",
    occasions:["Aniversário","Amizade","Parabéns","Pedido de Desculpas"],
    descricao:"O dente-de-leão transforma-se em sopro de vento.",
    preco:6.00, estoque:150 },

  { nome:"Trevo", especie:"Trifolium repens", cor:"Branco", emoji:"☘️", file:"trevo.png",
    feelings:["Esperança","Amizade"], meanings:["Sorte","Fé","Proteção"],
    colors:["Branco"], category:"Esperança", origin:"Europa", season:"Primavera",
    occasions:["Amizade","Parabéns","Aniversário","Gratidão"],
    descricao:"Diz a lenda que encontrar um trevo de quatro folhas traz sorte.",
    preco:7.00, estoque:130 },

  { nome:"Flor de Laranjeira", especie:"Citrus sinensis", cor:"Branco", emoji:"🍊", file:"flor_de_laranjeira.png",
    feelings:["Amor","Esperança"], meanings:["Pureza","Fertilidade","Casamento"],
    colors:["Branco"], category:"Pureza", origin:"Ásia", season:"Primavera",
    occasions:["Casamento","Dia dos Namorados","Gratidão","Aniversário"],
    descricao:"A flor de laranjeira é tradição em casamentos.",
    preco:22.00, estoque:40 },

  { nome:"Flor de Macieira", especie:"Malus domestica", cor:"Rosa", emoji:"🍎", file:"flor_de_maca.png",
    feelings:["Amor","Esperança"], meanings:["Amor","Promessa","Renovação"],
    colors:["Rosa","Branco"], category:"Amor", origin:"Europa", season:"Primavera",
    occasions:["Dia dos Namorados","Casamento","Aniversário","Gratidão"],
    descricao:"A flor de macieira anuncia a primavera e a promessa de frutos.",
    preco:19.00, estoque:50 },

  { nome:"Flor de Pessegueiro", especie:"Prunus persica", cor:"Rosa", emoji:"🍑", file:"flor_de_pessegueiro.png",
    feelings:["Amor","Esperança"], meanings:["Longevidade","Romance","Imortalidade"],
    colors:["Rosa"], category:"Amor", origin:"Ásia", season:"Primavera",
    occasions:["Dia dos Namorados","Aniversário","Casamento","Gratidão"],
    descricao:"Na China, a flor de pessegueiro é símbolo de longevidade e romance.",
    preco:19.50, estoque:48 },

  { nome:"Proteia", especie:"Protea cynaroides", cor:"Rosa", emoji:"🌱", file:"proteia.png",
    feelings:["Coragem","Esperança"], meanings:["Transformação","Coragem","Diversidade"],
    colors:["Rosa","Vermelho"], category:"Coragem", origin:"África do Sul", season:"Ano inteiro",
    occasions:["Parabéns","Aniversário","Gratidão","Pedido de Desculpas"],
    descricao:"A proteia é uma das flores mais antigas do planeta.",
    preco:38.00, estoque:18 },

  { nome:"Rosa-canina", especie:"Rosa canina", cor:"Rosa", emoji:"🥀", file:"rosa_canina.png",
    feelings:["Saudade","Amor"], meanings:["Simplicidade","Memória","Resiliência"],
    colors:["Rosa","Branco"], category:"Memória", origin:"Europa", season:"Primavera / Verão",
    occasions:["Condolências","Dia dos Namorados","Aniversário","Amizade"],
    descricao:"A rosa-canina é a rosa selvagem — simples, resistente e cheia de espinhos.",
    preco:14.00, estoque:60 },

  { nome:"Flor-de-lis", especie:"Iris pseudacorus", cor:"Amarelo", emoji:"⚜️", file:"flor_de_lis.png",
    feelings:["Esperança","Coragem"], meanings:["Realeza","Sabedoria","Inspiração"],
    colors:["Amarelo","Roxo"], category:"Esperança", origin:"Europa", season:"Primavera / Verão",
    occasions:["Parabéns","Aniversário","Gratidão","Casamento"],
    descricao:"A flor-de-lis é símbolo da realeza francesa e da sabedoria.",
    preco:18.00, estoque:45 },

  { nome:"Flor de Cacto", especie:"Cereus jamacaru", cor:"Branco", emoji:"🌵", file:"flor_de_cacto.png",
    feelings:["Esperança","Coragem"], meanings:["Resiliência","Beleza rara","Força"],
    colors:["Branco","Rosa"], category:"Esperança", origin:"América", season:"Verão",
    occasions:["Parabéns","Aniversário","Gratidão","Pedido de Desculpas"],
    descricao:"O cacto floresce no deserto, onde nada deveria florescer.",
    preco:24.00, estoque:30 },

  { nome:"Flor de Bordo", especie:"Acer", cor:"Vermelho", emoji:"🍁", file:"flor_de_bordo.png",
    feelings:["Saudade","Esperança"], meanings:["Outono","Mudança","Memória"],
    colors:["Vermelho","Laranja"], category:"Memória", origin:"América do Norte / Ásia", season:"Outono",
    occasions:["Condolências","Aniversário","Gratidão","Amizade"],
    descricao:"A flor de bordo anuncia o outono — estação das despedidas.",
    preco:16.00, estoque:55 },

  { nome:"Flor de Outono", especie:"Colchicum autumnale", cor:"Rosa", emoji:"🍂", file:"flor_de_outono.png",
    feelings:["Saudade","Tranquilidade"], meanings:["Renascimento","Ciclos","Serenidade"],
    colors:["Rosa","Lilás"], category:"Tranquilidade", origin:"Europa", season:"Outono",
    occasions:["Condolências","Aniversário","Gratidão","Amizade"],
    descricao:'Também chamada de "dama nua", floresce sem folhas no outono.',
    preco:15.00, estoque:50 },

  { nome:"Flor de Palmeira", especie:"Cocos nucifera", cor:"Amarelo", emoji:"🌴", file:"flor_de_palmeira.png",
    feelings:["Alegria","Esperança"], meanings:["Vitória","Tropicalidade","Fartura"],
    colors:["Amarelo","Branco"], category:"Prosperidade", origin:"Trópicos", season:"Ano inteiro",
    occasions:["Parabéns","Aniversário","Gratidão","Amizade"],
    descricao:"A flor de palmeira é discreta, mas anuncia os frutos que virão.",
    preco:12.00, estoque:70 },

  { nome:"Flor de Pinheiro", especie:"Pinus", cor:"Amarelo", emoji:"🌲", file:"flor_de_pinheiro.png",
    feelings:["Esperança","Tranquilidade"], meanings:["Eternidade","Resiliência","Paz"],
    colors:["Amarelo","Branco"], category:"Tranquilidade", origin:"Hemisfério Norte", season:"Primavera",
    occasions:["Condolências","Gratidão","Aniversário","Casamento"],
    descricao:"A flor de pinheiro é quase invisível, mas dá origem à árvore mais resistente.",
    preco:11.00, estoque:65 },

  { nome:"Flor de Bambu", especie:"Bambusa", cor:"Amarelo", emoji:"🎋", file:"flor_de_bambu.png",
    feelings:["Esperança","Amizade"], meanings:["Flexibilidade","Prosperidade","Paz"],
    colors:["Amarelo","Branco"], category:"Prosperidade", origin:"Ásia", season:"Ano inteiro",
    occasions:["Parabéns","Aniversário","Gratidão","Amizade"],
    descricao:"A flor de bambu é raríssima — algumas espécies florescem só uma vez a cada 100 anos.",
    preco:35.00, estoque:12 },

  { nome:"Flor de Jacarandá", especie:"Jacaranda mimosifolia", cor:"Roxo", emoji:"🌳", file:"flor_de_jacaranda.png",
    feelings:["Tranquilidade","Esperança"], meanings:["Serenidade","Renovação","Beleza"],
    colors:["Roxo","Lilás"], category:"Tranquilidade", origin:"América do Sul", season:"Primavera",
    occasions:["Aniversário","Gratidão","Casamento","Amizade"],
    descricao:"Quando o jacarandá floresce, ruas inteiras ficam lilás.",
    preco:26.00, estoque:22 },

  // --- Algumas adicionais para completar o catálogo ---
  { nome:"Rosa Branca", especie:"Rosa spp.", cor:"Branco", emoji:"🤍", file:"rosa_branca.png",
    feelings:["Pureza","Amor"], meanings:["Pureza","Inocência","Novo começo"],
    colors:["Branco"], category:"Pureza", origin:"Ásia", season:"Primavera / Verão",
    occasions:["Casamento","Condolências","Aniversário","Gratidão"],
    descricao:"A rosa branca representa pureza e novos começos.",
    preco:16.00, estoque:70 },

  { nome:"Rosa Amarela", especie:"Rosa spp.", cor:"Amarelo", emoji:"💛", file:"rosa_amarela.png",
    feelings:["Alegria","Amizade"], meanings:["Amizade","Alegria","Positividade"],
    colors:["Amarelo"], category:"Amizade", origin:"Ásia", season:"Primavera / Verão",
    occasions:["Amizade","Parabéns","Aniversário","Gratidão"],
    descricao:"A rosa amarela é a flor da amizade verdadeira.",
    preco:15.00, estoque:75 },

  { nome:"Tulipa Amarela", especie:"Tulipa gesneriana", cor:"Amarelo", emoji:"🌷", file:"tulipa_amarela.png",
    feelings:["Alegria","Esperança"], meanings:["Esperança","Alegria","Luz"],
    colors:["Amarelo"], category:"Alegria", origin:"Ásia Central", season:"Primavera",
    occasions:["Aniversário","Amizade","Parabéns","Gratidão"],
    descricao:"A tulipa amarela traz luz e esperança.",
    preco:18.00, estoque:55 },

  { nome:"Tulipa Vermelha", especie:"Tulipa gesneriana", cor:"Vermelho", emoji:"🌹", file:"tulipa_vermelha.png",
    feelings:["Amor","Paixão"], meanings:["Amor perfeito","Paixão","Declaração"],
    colors:["Vermelho"], category:"Amor", origin:"Ásia Central", season:"Primavera",
    occasions:["Dia dos Namorados","Casamento","Aniversário","Pedido de Casamento"],
    descricao:"A tulipa vermelha é declaração de amor.",
    preco:19.00, estoque:60 },

  { nome:"Cravina", especie:"Dianthus plumarius", cor:"Rosa", emoji:"🌸", file:"cravina.png",
    feelings:["Amor","Encanto"], meanings:["Encanto","Admiração","Fascínio"],
    colors:["Rosa","Vermelho"], category:"Admiração", origin:"Europa", season:"Primavera / Verão",
    occasions:["Aniversário","Amizade","Gratidão","Parabéns"],
    descricao:"A cravina é delicada e cheia de encanto.",
    preco:12.00, estoque:70 },

  { nome:"Alstroeméria", especie:"Alstroemeria", cor:"Rosa", emoji:"🌺", file:"alstroemeria.png",
    feelings:["Amizade","Amor"], meanings:["Amizade eterna","Prosperidade","Devoção"],
    colors:["Rosa","Roxo","Branco"], category:"Amizade", origin:"América do Sul", season:"Ano inteiro",
    occasions:["Amizade","Aniversário","Gratidão","Parabéns"],
    descricao:"A alstroeméria é símbolo de amizade eterna.",
    preco:17.00, estoque:60 },

  { nome:"Angélica", especie:"Angelica archangelica", cor:"Branco", emoji:"🤍", file:"angelica.png",
    feelings:["Espiritualidade","Proteção"], meanings:["Proteção","Inspiração","Cura"],
    colors:["Branco","Verde"], category:"Espiritualidade", origin:"Europa", season:"Verão",
    occasions:["Cerimônia Espiritual","Condolências","Gratidão","Aniversário"],
    descricao:"A angélica é associada a proteção e inspiração divina.",
    preco:23.00, estoque:35 },

  { nome:"Rosa Chá", especie:"Rosa × hybrida", cor:"Pêssego", emoji:"🌹", file:"rosa_cha.png",
    feelings:["Amor","Gratidão"], meanings:["Gratidão","Admiração","Simpatia"],
    colors:["Pêssego","Salmão"], category:"Gratidão", origin:"Cultivada", season:"Ano inteiro",
    occasions:["Gratidão","Aniversário","Amizade","Casamento"],
    descricao:"A rosa-chá é elegante e agradecida.",
    preco:17.50, estoque:55 },

  { nome:"Flor de Maracujá", especie:"Passiflora", cor:"Roxo", emoji:"💜", file:"flor_de_maracuja.png",
    feelings:["Espiritualidade","Tranquilidade"], meanings:["Fé","Serenidade","Paixão"],
    colors:["Roxo","Azul"], category:"Espiritualidade", origin:"América do Sul", season:"Verão",
    occasions:["Cerimônia Espiritual","Aniversário","Gratidão","Amizade"],
    descricao:"A flor do maracujá é símbolo da Paixão de Cristo.",
    preco:14.00, estoque:45 },

  { nome:"Flor de Ipê", especie:"Tabebuia", cor:"Amarelo", emoji:"🌻", file:"flor_de_ipe.png",
    feelings:["Esperança","Alegria"], meanings:["Renovação","Esperança","Brasilidade"],
    colors:["Amarelo","Rosa"], category:"Esperança", origin:"Brasil", season:"Primavera",
    occasions:["Aniversário","Gratidão","Parabéns","Amizade"],
    descricao:"Quando o ipê floresce, o Brasil inteiro se colore.",
    preco:20.00, estoque:30 }
];

async function seedFlores() {
  try {
    const total = await Flor.estimatedDocumentCount();
    if (total > 0) {
      console.log(`[seed] ${total} flores já cadastradas — pulando seed.`);
      return;
    }
    await Flor.insertMany(FLORES_SEED);
    console.log(`[seed] ✅ ${FLORES_SEED.length} flores inseridas com sucesso.`);
  } catch (err) {
    console.error("[seed] ✖ Erro ao popular flores:", err.message);
  }
}

module.exports = seedFlores;